### ISSUE TITLE
Layer shift

### ISSUE THREAD

**Issue by drivernn** [makerbase-mks/MKS-TinyBee#10]
Layer shift by 1-2 mm on long prints for no apparent reason. 
The motor currents are sufficient, the speeds are small, about 80-100 mm/sec.

**Comment by MKS-hosiey** [comment]
Hello, is there a print offset? Is it every time?

**Comment by drivernn** [comment]
Hey! This is about one in 3-5 times for print times over 1 hour.
I plan to experiment with the size of BLOCK_BUFFER_SIZE and BUFSIZE.

**Comment by drivernn** [comment]
I ordered and received a new motherboard. All problems have been resolved. Unfortunately, the first faulty motherboard took me a lot of time and effort.
