### ISSUE TITLE
Problem with MKS_MINI_12864

### ISSUE THREAD

**Issue by Norgulin** [makerbase-mks/MKS-TinyBee#12]
The firmware after a recent update is compiled, but the screen does not work, it just glows and that's it.

**Comment by MKS-hosiey** [comment]
Please update our github latest firmware, the issue is fixed

**Comment by Sergio-M-web** [comment]
O MKS MINI 12864 não acende a luz de fundo mesmo habilitando  NEOPIXEL_LED.
