### ISSUE TITLE
Pin connection for Endstops

### ISSUE THREAD

**Issue by countcobolt** [makerbase-mks/MKS-TinyBee#16]
Hi all,

I am using the standard creality end stop. They have a S G and V pin out. I tried connecting them according to the pin out of the tinybee, but when I plug them in, the mainboard goes in error. What is the correct connection for these type of endstops?

Kind regards

Steve

**Comment by MKS-hosiey** [comment]
Hello, you can connect the s and g of enstop to the s and g of enstop of the main board, no need to connect V, if your limit output signal is 5V, this will affect the internal voltage of esp32, resulting in inaccurate temperature measurement, and an error will be reported

**Comment by countcobolt** [comment]
Hi, I indeed got is solved that way. Thanks
