### ISSUE TITLE
MKS Tinybee error 

### ISSUE THREAD

**Issue by flishy2532** [makerbase-mks/MKS-TinyBee#29]
any one can help i have this error!

**Comment by flishy2532** [comment]
![20220509_010259.jpg](https://user-images.githubusercontent.com/61683774/167309288-f6ee03d7-80ea-4c3d-86e0-c8a614ab6147.jpg)

**Comment by MKS-hosiey** [comment]
The yellow part is a warning, and the red part is an error. Can you take a screenshot of the red font part?

**Comment by flishy2532** [comment]
am try find what wronge in this problem am new in platformio any one can help 
old version am use arduino ide it no problem with old motherboard compile but old motherboard is broke (Trigorilla i think original)
![20220509_142751.jpg](https://user-images.githubusercontent.com/61683774/167361121-1f66f537-9893-45d1-b64f-ff80ecdc1689.jpg)

am change to this mks tiny bee
but it layer shift on height print at 73% on cura i dont know what problem on config am use tmc2209 x4 v1.0 on this mks tiny bee
sdcard work
wifi work - esp32 wifi 
screen work - mks_mini v3 with neopixel (cycle color start up)

![20220509_143218.jpg](https://user-images.githubusercontent.com/61683774/167362311-48546c3f-aef3-46f0-a8ef-38f6867ce779.jpg)

![20220509_143742.jpg](https://user-images.githubusercontent.com/61683774/167362569-ca0d48b0-ef85-436a-bdb4-de9d8c8bcacf.jpg)

any one can help ? and teach me for platformio
 thank you 
best reguard

**Comment by flishy2532** [comment]
did you have delta printer on mks tiny bee?

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________
