### ISSUE TITLE
Power supply 12V/24V

### ISSUE THREAD

**Issue by netisis** [makerbase-mks/MKS-TinyBee#3]
Hello,
I have a 12V 20A power supply, I see that on the board there are 12V and 24V outputs, would I have 24V output with a 12V power supply. (i have a 24V heat bed)
Does the card have a DC-DC converter?
Thanks for your answer.

**Comment by MKS-hosiey** [comment]
The output voltage is determined by your input voltage, input 12V, the output is 12V, the port of the motherboard means that the motherboard can input 12/24V
