### ISSUE TITLE
MKS Plugin for Cura

### ISSUE THREAD

**Issue by syntax1269** [makerbase-mks/MKS-TinyBee#32]
I am currently using the MKS Wii Plugin with Cura and doesn't work at all. Is there an updated cura plugin or maybe settings that i might have missed? I can upload via the webGUI but only able to get 8 character filenames. Uploading from cura fails everytime. Also when monitoring in cura, only getting hotend temp and not bed.

**Comment by MKS-hosiey** [comment]
You can download our latest cura plugin, it already supports tinybee

**Comment by flishy2532** [comment]
i have same problem and marlin 2.0.9.2 layershift too

**Comment by syntax1269** [comment]
I am currently using Cura 4.13.1 and the plugin version 1.3.2 
Is there something i am missing or settings somewhere to enable this? Is there another place to download the plugin that works with tinybee? I am also using the latest marlin 2.0.9.2 from here also.

**Comment by flishy2532** [comment]
Can control but send file to printer always fail


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
