### ISSUE TITLE
CR-10 screen does not work well

### ISSUE THREAD

**Issue by boshiue** [makerbase-mks/MKS-TinyBee#35]
I would like to use Tinybee to replace my ender3 pro MotherBroad, but When I use #define CR10_STOCKDISPLAY for LCD the tune bottom doesn't work well.(I can press the bottom but can't go up and down). Is anyone have this problem?

**Comment by boshiue** [comment]
connect EXP1 EXP2 then the issue fixed...

**Comment by boshiue** [comment]
connect EXP1 EXP2 then the issue fixed...

**Comment by jaymcd** [comment]
?? How does trhat solve the problem?

**Comment by georgekucher** [comment]
> connect EXP1 EXP2 then the issue fixed...

what exactly did you connect to what?
