### ISSUE TITLE
NEOPIXEL_LED Backlight

### ISSUE THREAD

**Issue by drivernn** [makerbase-mks/MKS-TinyBee#4]
Hello! The backlight of the MKS MINI 12864 V3.0_002 screen does not work.  
Please tell me what needs to be fixed? 
Thanks!

![0032](https://user-images.githubusercontent.com/97470978/148819721-29d8b233-2d89-4a82-8b8c-934971d409e0.jpg)

**Comment by drivernn** [comment]
Am I the only one having problems with NEOPIXEL_LED Backlight? Does everyone else work?

**Comment by drivernn** [comment]
New software don't compile with MKS MINI 12864 V3.0 .

![16-01-2022 231139](https://user-images.githubusercontent.com/97470978/149683627-857f5426-0e73-4ba7-a5c4-0a05067de05b.jpg)

**Comment by MKS-hosiey** [comment]
Is your firmware downloaded from our github or from marlin's page?

**Comment by drivernn** [comment]
Yes, from here https://github.com/makerbase-mks/MKS-TinyBee/tree/main/firmware .

**Comment by wirebeard** [comment]
Same error on firmware from Marlin page https://github.com/MarlinFirmware/Marlin.git
![Marlin compile error](https://user-images.githubusercontent.com/13260728/149882265-21c4fe91-9d59-41c4-a623-c1c4d4608e76.JPG)

**Comment by MKS-hosiey** [comment]
Please send your email address, I will send you the firmware that I tested and compiled normally

**Comment by drivernn** [comment]
My email address  yyyyymail@yandex.ru .  I will be very grateful for a working firmvere.

**Comment by ellensp** [comment]
see https://github.com/MarlinFirmware/Marlin/issues/23561  for the not compiling issue

MKS added the file Mrlin/src/HAL/ESP32/u8g_esp32_spi.cpp but it has a bug

The file start with #ifdef MKS_MINI_12864_V3 but this is checked before the Config files are loaded, so it always fails

Change the start to  
#include "../../inc/MarlinConfigPre.h"
#ifdef MKS_MINI_12864_V3

and delete the 2nd #include "../../inc/MarlinConfigPre.h" line lower down

**Comment by drivernn** [comment]
Thanks! It compiles, but there are still problems.

![19-01-2022 230058](https://user-images.githubusercontent.com/97470978/150206307-7516084a-231e-4618-b71b-119be2ba8843.jpg)

**Comment by ellensp** [comment]
@drivernn that is a com port issue on your machine...    "could not open port `COM9`"   
Its windows, you probably need to reboot as windows has a bad habit of locking com ports.

**Comment by wirebeard** [comment]
Firmware compile on Windows 10 with PlatformIO (VSC)  and on Debian 11 with PlatformIO Core (CLI)

**Comment by drivernn** [comment]
The first version of the firmware, which was here on github, compiles and works without problems. It had only one problem with the lack of a NEOPIXEL_LED control signal. Is it possible to fix just this minor problem without ruining everything else? )

**Comment by drivernn** [comment]
p.s. The problem here is not with the com9 port on my computer, but with the PlatformIO configuration file. I know how to fix it. But I would like to see the official fully working firmware for the standard MKS TinyBee + MKS MINI12864 V3 kit. Unfortunately, such firmware does not exist yet.

**Comment by solawc** [comment]
The problem described above has been resolved on the newly updated firmware, and you can download the new one to try. In addition, the default download port specified by the previous firmware is COM9. Now this default download port has been removed. You can see the setting under esp32.ini.

**Comment by drivernn** [comment]
Thanks! However, in your latest firmware, MKS_MINI_12864_V3 is enabled again, but //#define NEOPIXEL_LED is disabled. How can the backlight of this screen work??? Is it possible to make a fully working firmware to work with this screen, which is sold in the kit?

**Comment by michaelslobodskih** [comment]
> Thanks! However, in your latest firmware, MKS_MINI_12864_V3 is enabled again, but //#define NEOPIXEL_LED is disabled. How can the backlight of this screen work??? Is it possible to make a fully working firmware to work with this screen, which is sold in the kit?

Download latest firmware , uncomment MKS_MINI_12864_V3. Everything works fine (after enabing there are menu for backligth configuration).

**Comment by drivernn** [comment]
I ordered and received a new motherboard. All problems have been resolved. Unfortunately, the first faulty motherboard took me a lot of time and effort.
