### ISSUE TITLE
Factory reset ESP3D wifi settings

### ISSUE THREAD

**Issue by 3DSmitty** [makerbase-mks/MKS-TinyBee#40]
Wifi settings were set wrong and now it does not connect to wifi. How do I reset them to factory without access to the WEBUI???

**Comment by flishy2532** [comment]
what do you set wrong? did you turn off http protocal ?

**Comment by 3DSmitty** [comment]
No I accidentally entered the wrong wifi pwd. All fixed now using M118 command from pronterface.
