### ISSUE TITLE
unable to use RepRap 2004 display module

### ISSUE THREAD

**Issue by HiIamChaitanya** [makerbase-mks/MKS-TinyBee#45]

**Comment by jaymcd** [comment]
How was this resolved?

**Comment by HiIamChaitanya** [comment]
I enabled other displays as well thus was having error

**Comment by jaymcd** [comment]
Ok it s sounds like there is some pin definition issues or non standard display/cable arrangement.Jay M McDonaldOn Dec 9, 2022, at 8:51 PM, Chaitanya ***@***.***> wrote:﻿
I enabled other displays as well thus was having error

**Comment by HiIamChaitanya** [comment]
yep, you have to comment other display

**Comment by jaymcd** [comment]
I have the right display identified in Marlin. That is not the issue,Jay M McDonaldOn Dec 9, 2022, at 9:30 PM, Chaitanya ***@***.***> wrote:﻿

yep , you have to comment other display

**Comment by HiIamChaitanya** [comment]
then you might have missing lib or can you share their terminal logs / error

**Comment by jaymcd** [comment]
I received my MKS Mini 12864 V3 - it does not work with my Tiny Bee either. Defined in Marlin as the MKS Mini 12864 V3 but does not even light up. 

Do I have a defective Tiny Bee board ? 

Jay
