### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

### ISSUE THREAD

**Issue by verissimoster** [makerbase-mks/MKS-TinyBee#49]
Whenever I try to flash the FW I always get the error:

Uploading .pio\build\mks_tinybee\firmware.bin
esptool.py v3.0
Serial port COM5
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
*** [upload] Error 2
======================================================= [FAILED] Took 274.93 seconds =======================================================

Environment    Status    Duration
-------------  --------  ------------
mks_tinybee    FAILED    00:04:34.931

I saw the Topic "USB Doesn't work", but come on I bought a fully functional board and now I'm the one who needs to repair it?! Waiting for feedback from your customer support

**Comment by DrainIT** [comment]
I had the same problem. In the opposite corner to the heaters cable and the stepper drivers -near the thermistor sensors cables- there is a button .
Just start uploading, push the button and DON'T release it until the "connecting" prompt appears, that should be similar in every uploading program you're using - i was using VS code. If it doesn't work, try pressing it for 5 seconds - it should flash red, meaning it's ready for the uploading.
I hope that helped.

**Comment by jirka-malvin** [comment]
are you using Mac? if yes, do you have driver for ESP installed?

**Comment by verissimoster** [comment]
hello guys, tks for your help, I solve the problem by changing the computer, fortunately I do have another one at home, and worked just fine.

**Comment by Rmdhn1** [comment]
have this issue, used to work, don't know why it's suddenly like this

**Comment by Rmdhn1** [comment]
UPDATE : Accidentally plugged in to USB 2.0,
MUST USE 3.0

**Comment by ntsub** [comment]
I have still the same problem, uploading on a 3.0 USB with a relatibe short USB cable.
any other idea?

**Comment by ntsub** [comment]
SD CART uploading firware.bin does neither work... :(
Totally lost

**Comment by guigur** [comment]
got the error on my macbook but it works on my windows desktop

**Comment by sebmorales** [comment]
any other ideas on how to fix this on a mac? I have the same problem. Pressing the button during upload (until "connecting") didn't help.

**Comment by ntsub** [comment]
The only good typ was to apply a powered USB. I donnot know if it works or
not, because of lack of time and paralel projects

El ds., 15 de febr. 2025, 21:07, seb ***@***.***> va escriure:
