### ISSUE TITLE
Information missing from the WebUI

### ISSUE THREAD

**Issue by Caian** [makerbase-mks/MKS-TinyBee#59]
I've cloned the latest version (5f248e6a6cd968b85ac0a9818a4e4b48c0eca5c2) of this repository, built and flashed the firmware without any issues, managed to connect to the printer and upload the WebUI gz file that is also in this commit.

The printer is connected to my home WiFi and printing from the WebUI without issues, however, it is not showing information like the temperature graph, also all commands in the command panel only return "Ok", even those that are supposed to return additional information like `M105`, `M118`,...

How do I fix this issue?

**Comment by jirka-malvin** [comment]
in the right top corner -> check every 3 seconds ... 
<img width="736" alt="Snímek obrazovky 2022-10-07 v 18 13 22" src="https://user-images.githubusercontent.com/10552806/194599806-ae3412eb-9d73-4fae-882c-60b289795dba.png">

**Comment by Caian** [comment]
Already tried, the horizontal lines of the graph show up, but nothing is plotted.

**Comment by jirka-malvin** [comment]
<img width="704" alt="Snímek obrazovky 2022-10-07 v 20 45 52" src="https://user-images.githubusercontent.com/10552806/194628274-21ff472f-93f1-49d8-8224-b1431472cfe5.png">

It shoul looks like this pisture ... At me - this is working

**Comment by Caian** [comment]
I found the issue, I was tunneling my connection through `ssh` into my network. But apparently ESP32Lib creates a websocket for the WebUI that is not being tunneled.
