### ISSUE TITLE
What do three flashing red lights mean (just above fan 2 connector)

### ISSUE THREAD

**Issue by jaymcd** [makerbase-mks/MKS-TinyBee#73]
My board is flashing three red lights . I can't find any info on this .....????

**Comment by ghost** [comment]
The red LEDs are the indicators for the heater and fan outputs. They light up when an output is powered.

**Comment by jaymcd** [comment]
ThanksJay M McDonaldOn Jan 12, 2023, at 8:50 PM, Raphael Böhm ***@***.***> wrote:﻿
The red LEDs are the indicators for the heater and fan outputs. They light up when an output is powered.

**Comment by ghost** [comment]
Would you mind closing this issue?

**Comment by jaymcd** [comment]
Thanks for the info
