### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by YoshiAye** [makerbase-mks/MKS-TinyBee#8]
I'm using latest files from [here](https://github.com/makerbase-mks/MKS-TinyBee), and anytime I'm changing MKS_MINI_12864_V3 to MKS_MINI_12864 in Configuration.h I'm getting:
```
Linking .pio\build\mks_tinybee\firmware.elf
.pio/build/mks_tinybee/src/src/lcd/dogm/u8g_dev_uc1701_mini12864_HAL.cpp.o:(.data.u8g_dev_uc1701_mini12864_HAL_2x_hw_spi+0x8): undefined reference to `u8g_eps_hw_spi_fn(_u8g_t*, unsigned char, unsigned char, void*)'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\mks_tinybee\firmware.elf] Error 1
```
Without any changes it compiles without errors.

**Comment by Norgulin** [comment]
Same problem with MKS_LCD12864B
![image](https://user-images.githubusercontent.com/99501731/153645176-74d28876-adcf-4408-94ce-6040300122e2.png)

**Comment by YoshiAye** [comment]
> Same problem with MKS_LCD12864B ![image](https://user-images.githubusercontent.com/99501731/153645176-74d28876-adcf-4408-94ce-6040300122e2.png)

This is email that I got from them: This is because the library of the new version of the marlin firmware may be missing. We will let engineers fix this, and then feedback to marlin official for modification.

So I guess we should open issue on marlin git.
