### ISSUE TITLE
MKS tinybee board

### ISSUE THREAD

**Issue by ahmedhassan3298** [makerbase-mks/MKS-TinyBee#88]
Hi all,
my MKS tinybee board give error in temperature when i connect end stop for y-axis
![WhatsApp Image 2023-05-02 at 14 24 55](https://user-images.githubusercontent.com/132415206/235816724-056f120b-d2b1-4fed-8d5c-09c746c559e8.jpg)
![WhatsApp Image 2023-05-02 at 14 24 56](https://user-images.githubusercontent.com/132415206/235816732-a4267704-5687-4b0c-8068-dc80391281cc.jpg)

**Comment by enddDD** [comment]
https://github.com/makerbase-mks/MKS-TinyBee/issues/36
Check this, maybe it helps you. Try using only 2 pins for the endstops

**Comment by ahmedhassan3298** [comment]
Thanks for your help
I Try 2 pins (S,G) for the end stop The end stop dont stop the motor

**Comment by enddDD** [comment]
Is it tied NC (normally closed) the switch? If the switch has 3 pins u should tie the two from each side and leave the middle pin unconnected. Also make sure it is in the right axis slot, x, y, z

**Comment by ahmedhassan3298** [comment]
![Screenshot_2023-05-03-16-21-54-981_com.android.chrome.png](https://user-images.githubusercontent.com/132415206/235928642-7dd9ec02-15ab-42eb-9e77-4f1311053e55.png)

i use this type of endstop i disconnect the red wire
