### ISSUE TITLE
If INPUT SHAPING is activated, the auto home function does not work.

### ISSUE THREAD

**Issue by vfbank** [makerbase-mks/MKS-TinyBee#92]
I am using the Marlin 2.1.x bugfix. When INPUT SHAPING is activated, after touching the X-axis limit switch, it stops immediately. Has anyone else experienced this problem and found a solution?

**Comment by PanosPetrou** [comment]
This board uses I2S Stream (most ESP32 based boards do). Input Shaping, FT Motion and to some extend Linear Advance, won't work, because currently these features are not compatible with I2S Stream.

**Comment by vfbank** [comment]
> 

I just found out why people don't use this board. Thanks for answering my question.
